[DataGrid] Add filter fix
mui-org/material-ui-x pull request #1029
Opened 2021-02-11 11:16 UTC by dtassone

fix #1026

2021-02-11 11:19 UTC, dtassone commented on packages/storybook/src/stories/grid-filter.stories.tsx
>        ratingColumn!.filterOperators = ratingOperators.map((operator) => {
All filters stories that changes the columns are broken due #979

2021-02-11 11:19 UTC, dtassone commented
waiting for #1024

2021-02-11 11:49 UTC, oliviertassinari requested changes

2021-02-11 11:49 UTC, oliviertassinari commented on packages/grid/_modules_/grid/components/panel/filterPanel/FilterPanel.tsx
> +            className="MuiAddFilterButton"
```suggestion
```

2021-02-11 11:49 UTC, oliviertassinari commented on packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx
> +      const addButton = document.querySelector(`.MuiAddFilterButton`);
use the accessibility tree

2021-02-11 11:49 UTC, oliviertassinari commented on packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx
> -} from 'test/utils';
Why this diff? Could we minimize them?

On a related note, I believe that so far, the approach is to import the most common modules first, e.g. react, then sinon, then test utils, then the module we test.

2021-02-11 11:49 UTC, oliviertassinari commented on packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx
> +      expect(filterForms.length).to.eq(2);
We should likely make this alias throw in the setup

```suggestion
      expect(filterForms.length).to.equal(2);
```

or maybe better

```suggestion
      expect(filterForms).to.have.length(2);
```

2021-02-11 11:49 UTC, oliviertassinari commented on packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx
> +          }, Math.random() * 500 + 100); // simulate network latency
This Math.random() and setTimeout are red flags. Please simplify the test case as much as possible to nail the root cause (failing on master). We don't need the ceremony.

2021-02-11 18:20 UTC, oliviertassinari approved these changes

2021-02-11 18:24 UTC, oliviertassinari commented
I have pushed 3 commits to simplify the tests

2021-02-12 08:58 UTC, DanailH approved these changes

2021-02-12 09:34 UTC, merged