[Test] Add expand cell renderer
mui-org/material-ui-x pull request #1070
Opened 2021-02-17 15:50 UTC by dtassone

Add expand cell story

/?path=/story/x-grid-tests-rows--expend-row-cell

2021-02-17 18:57 UTC, oliviertassinari reviewed
What's the use case for adding the demo in the stories? It's not in the documentation so developers can't find it. It's not in the automation test so won't help catch regression.

2021-02-18 09:36 UTC, DanailH commented
Isn't this just to showcase that it is possible. I would agree that it is probably more appropriate to add it as a demo in the docs.

2021-02-18 10:09 UTC, dtassone commented
I put it somewhere fit to save it. If you want we can put it in the doc.
Or we could create an option in colDef so we could use it if the cell is overflown

2021-02-18 10:37 UTC, oliviertassinari commented
> I put it somewhere fit to save it.

For saving it, I would argue copying the sources in GitHub + saving the codesandbox under mui-org would be enough. At least, it's what we have done in the main repo, we have thousands of similar demos like this.

2021-02-18 11:45 UTC, dtassone commented
> > I put it somewhere fit to save it.
> 
> For saving it, I would argue copying the sources in GitHub (in the relevant issue) + saving the codesandbox under mui-org is enough. At least, it's what we have done in the main repo, we have a lot of similar demos like this.

Having it in the storybook also allows to save it and come back to it easily. The main goal is to keep it close to our source code and if there is a breaking change we could easily upgrade it.

2021-02-18 11:51 UTC, oliviertassinari reviewed
>  if there is a breaking change

One of my concerns is that it will be hard to know if there is a breaking change.

If it was in the docs, developers would tell us. If it was in the GitHub issues, developers would tell us too. In the storybook, unless it crashes the build I don't see how we could ever know. We would rely on us being careful enough to upgrade all the stories when we do a breaking change. 

My second concern is that stories should be for internal development only, I don't really see who this will help.

2021-02-18 15:34 UTC, dtassone commented
> > if there is a breaking change
> 
> One of my concerns is that it will be hard to know if there is a breaking change.
> 
> If it was in the docs, developers would tell us. If it was in the GitHub issues, developers would tell us too. In the storybook, unless it crashes the build I don't see how we could ever know. We would rely on us being careful enough to upgrade all the stories when we do a breaking change.
> 
> My second concern is that stories are for internal development only, I don't really see who this will help.



> > if there is a breaking change
> 
> One of my concerns is that it will be hard to know if there is a breaking change.

The code should not compile, hence why we use typescript

> 
> If it was in the docs, developers would tell us. If it was in the GitHub issues, developers would tell us too. In the storybook, unless it crashes the build I don't see how we could ever know. We would rely on us being careful enough to upgrade all the stories when we do a breaking change.
> 
> My second concern is that stories are for internal development only, I don't really see who this will help.

this would help us in the long term
Also I think we should add a column in employee or commodities to showcase this option.

2021-02-18 15:42 UTC, oliviertassinari commented
> The code should not compile, hence why we use typescript

Sometimes, but it's far from enough if we want the demo to keep working in the long term. If had to guess, I would say that TypeScript catches 20% of the regressions that could happen. In this paper, they estimate it to 15% https://blog.acolyer.org/2017/09/19/to-type-or-not-to-type-quantifying-detectable-bugs-in-javascript/. We should be able to find more studies in the literature with similar order of magnitude. 

> would help us in the long term

Exactly, it's my question, how?

2021-02-18 15:50 UTC, oliviertassinari approved these changes

2021-02-18 15:51 UTC, oliviertassinari commented
It would probably be better to merge #1069 first, as this one would create a conflict

2021-02-18 15:57 UTC, dtassone commented
> > The code should not compile, hence why we use typescript
> 
> Sometimes, but it's far from enough if we want the demo to keep working in the long term. If had to guess, I would say that TypeScript catches 20% of the regressions that could happen. In this paper, they estimate it to 15% https://blog.acolyer.org/2017/09/19/to-type-or-not-to-type-quantifying-detectable-bugs-in-javascript/. We should be able to find more studies in the literature with similar order of magnitude.
> 
> > would help us in the long term
> 
> Exactly, it's my question, how?

I don't understand why it is such an issue.
Having commodities example or employee is as useful.
It's all about checking how things work, perform and interact together.

About TS, bringing one article out of the blue might not be that relevant as there is always a counterargument. Maybe looking at the typescript adoption curve might be more relevant. 
Also if you don't use types in your code, obviously the compiler won't break (or if you don't use type checking). So if 85% of ppl don't type their code properly then TS can't do anything for you. 
Things break at runtime, typing is all about catching this issue at compile time.

2021-02-18 16:19 UTC, oliviertassinari commented
> I don't understand why it is such an issue.

It's not an issue on its own. My concern is that we are not as efficient as we could be. I don't really get the tradeoff. From my perspective, either it's important and hence it should have its own demo in the documentation, or it's not and a codesandbox solve a similar problem. Now, I get that adding a stories can help catch some of the regressions with TypeScript. I also think that it comes with a cost. What I like about the codesandbox driven demos is that if we break it and it's not important we don't have to pay the maintenance price for it. If we do break it and it's important, a developer will likelyy raise it. We can try both

> About TS

Is simply think that types won't catch most of the regressions (probably about 20% of the regressions we might introduce). You don't have to trust me or the studies. We can give it a try and see how it goes. I talk from my experience in the main repo. We have migrated all the demos to TypeScript more than a year ago. We keep breaking them without knowing, developers open us bugs to report them.

> Having commodities example or employee is as useful.

From what I understand we have discussed moving them to the documentation under a demo page.

2021-02-18 16:32 UTC, dtassone commented
> From what I understand we have discussed moving them to the documentation under a demo page.

Having those demos are all about recreating real world use cases and having them in the storybook is also useful to debug any issues that could arise with those type of use cases.

IMO, we should integrate this renderer in employee to see how it performs in large dataset, and it will also be part of the showcase demos in the docs which is nice too

2021-02-18 18:51 UTC, dtassone commented
let me know what you think about the integration in employee or commodities...

2021-02-18 19:06 UTC, oliviertassinari commented
> let me know what you think about the integration in employee or commodities...

Regarding an expanded cell renderer in the default data sets, I don't have a preference. A few factors I think we can take into account:

- It can showcase the composability feature which is great
- The UX of the pattern itself has limits. Maybe we could try a trigger on click instead of on hover? I personally often get stuck with a pop-up, it's disturbing. If we keep a hover trigger, I think that we should fix this accessibility criterion: https://www.w3.org/TR/WCAG21/#content-on-hover-or-focus. An <kbd>Escape</kbd> as in https://github.com/mui-org/material-ui/pull/22376 would work.
- Is this feature often required by developers using a custom grid?

2021-02-20 11:13 UTC, oliviertassinari commented
This UX seems to deliver better:

<img width="522" alt="Capture d’écran 2021-02-20 à 12 11 40" src="https://user-images.githubusercontent.com/3165635/108593602-e62c5e00-7374-11eb-9cb6-ff7055b1433b.png">

Once a cell is hover, because it displays "over", you can still move your mouse down to move to the next item.

2021-02-22 12:04 UTC, DanailH approved these changes

2021-02-22 12:42 UTC, oliviertassinari commented
As a side note, I have tried to improve the demo in https://github.com/mui-org/material-ui-x/issues/417#issuecomment-782772202, using fewer hooks, computing value at the last possible moments fix Escape 1.4.13 accessibility criterion.

2021-02-22 18:47 UTC, oliviertassinari requested changes

2021-02-22 18:47 UTC, oliviertassinari commented on docs/src/pages/components/data-grid/rendering/RenderExpandCellGrid.tsx
> +import { Typography } from '@material-ui/core';
```suggestion
import Typography from '@material-ui/core/Typography';
```

2021-02-22 18:47 UTC, oliviertassinari commented on docs/src/pages/components/data-grid/rendering/RenderExpandCellGrid.tsx
> +      },
Deal code

```suggestion
```

2021-02-22 18:47 UTC, oliviertassinari commented on docs/src/pages/components/data-grid/rendering/RenderExpandCellGrid.tsx
> +          open={showFullCell && anchorEl != null}
It seems that it can't be undefined

```suggestion
          open={showFullCell && anchorEl !== null}
```

2021-02-22 18:47 UTC, oliviertassinari commented on docs/src/pages/components/data-grid/rendering/rendering.md
> +#### Expand Cell Renderer
```suggestion
#### Expand cell renderer
```

2021-02-22 18:47 UTC, oliviertassinari commented on docs/src/pages/components/data-grid/rendering/rendering.md
> +As workaround, you can create a cell renderer that will allow seeing the full content of the cell in the grid.
```suggestion
As a workaround, you can create a cell renderer that will allow seeing the full content of the cell in the grid.
```

2021-02-22 18:47 UTC, oliviertassinari commented on docs/src/pages/components/data-grid/rendering/rendering.md
> +By default, the grid will cut the content of a cell and render an ellipsis if the content of the cell does not fit in the cell.
```suggestion
By default, the grid cuts the content of a cell and renders an ellipsis if the content of the cell does not fit in the cell.
```

2021-02-22 18:47 UTC, oliviertassinari commented on docs/src/pages/components/data-grid/rendering/RenderExpandCellGrid.tsx
> +      <DataGrid rows={rows} columns={columns} hideFooter />
Unrelated

```suggestion
      <DataGrid rows={rows} columns={columns} />
```

2021-02-23 13:32 UTC, dtassone commented
@oliviertassinari I'm having issues with this build. It keeps failing, either lint due to unused proptypes and then docs formatted due to missing proptypes. So stuck in an infinite loop :P

2021-02-23 14:06 UTC, oliviertassinari commented
@dtassone I don't get why .propTypes is still added. I have moved your demo to the main repo and we don't get this issue. I think that @eps1lon has fixed this problem at some point So I won't worry too much about it. We will get it for free, once we upgrade the docs infra from v4 to v5. For context, the issue is:

```tsx
function renderCellExpand(params: GridCellParams) {
  return (
    <GridCellExpand
      value={params.value ? params.value.toString() : ''}
      width={params.colDef.width}
    />
  );
}
```

that turns into:

```jsx
function renderCellExpand(params) {
  return (
    <GridCellExpand
      value={params.value ? params.value.toString() : ''}
      width={params.colDef.width}
    />
  );
}

renderCellExpand.propTypes = {
  /**
   * The column of the row that the current cell belongs to.
   */
  colDef: PropTypes.any.isRequired,
  /**
   * The cell value, but if the column has valueGetter, use getValue.
   */
  value: PropTypes.oneOfType([
    PropTypes.instanceOf(Date),
    PropTypes.number,
    PropTypes.object,
    PropTypes.string,
    PropTypes.bool,
  ]),
};
```

2021-02-24 13:12 UTC, dtassone commented
@oliviertassinari did I override your changes?

2021-02-24 13:21 UTC, oliviertassinari commented
> did I override your changes?

Yes, it's fine. You can apply the fix back.

2021-02-24 13:21 UTC, oliviertassinari commented
> did I override your changes?

Yes, it's fine. You can apply the fix back.

2021-02-24 16:32 UTC, dtassone commented
> > did I override your changes?
> 
> Yes, it's fine. You can apply the fix back.

I can't I don't have it on my origin. Can you push it again please?

2021-02-24 16:41 UTC, oliviertassinari commented
@dtassone I didn't meant to cherry-pick the same solution, but to reapply the same strategy.

2021-02-24 22:34 UTC, oliviertassinari approved these changes

2021-02-25 10:04 UTC, merged