[docs] Clarify feature split
mui-org/material-ui-x pull request #1080
Opened 2021-02-19 11:34 UTC by oliviertassinari

Closes #1078

2021-02-19 12:03 UTC, oliviertassinari commented on docs/src/pages/components/data-grid/columns/columns.md
> +## Column resizing [<span class="pro"></span>](https://material-ui.com/store/items/material-ui-enterprise/)
We will point the /pricing page in the future, this is temporary

2021-02-19 12:19 UTC, oliviertassinari commented on docs/src/pages/components/data-grid/columns/columns.md
> +## Column resizing [<span class="pro"></span>](https://material-ui.com/store/items/material-ui-pro/)
It's temporary. It will point to the `/pricing` page in the future.

2021-02-19 12:20 UTC, oliviertassinari commented
@Sd100 Does it clarify it?

2021-02-19 12:46 UTC, oliviertassinari commented on README.md
> +We have been building MIT React components since 2014. we have learned a lot about the strength and weaknesses of the MIT license model. We believe that any open source project will ultimately become
*ultimately* means that commercial components can't be our end-goal, hence the need for a low-code shift going forward.

2021-02-20 00:24 UTC, oliviertassinari commented on README.md
> +We have been building MIT React components since 2014. we have learned a lot about the strength and weaknesses of the MIT license model. We believe that any open source project will ultimately become
I have first hard that from WordPress's founder: https://youtu.be/49HSZ4JQlHY?t=285

2021-02-21 04:40 UTC, mbrookes requested changes

2021-02-21 04:40 UTC, mbrookes commented on README.md
> +This Material-UI X mono-repo gathers the Material-UI advanced components. It's an extension of the core. The most fundamental features are MIT licensed and the most advanced ones commercial.
```suggestion
This Material-UI X mono-repo gathers the advanced Material-UI components – it's an extension of the core. The fundamental features are MIT licensed, and the more advanced ones commercial.
```

2021-02-21 04:40 UTC, mbrookes commented on README.md
> +We have been building MIT React components since 2014.
```suggestion
We have been building MIT React components since 2014,
```

2021-02-21 04:40 UTC, mbrookes commented on README.md
> +We have learned a lot about the strength and weaknesses of the MIT license model.
```suggestion
and have learned much about the strengths and weaknesses of the MIT license model.
```

2021-02-21 04:40 UTC, mbrookes commented on README.md
> +However, we believe that have reached the sustainability limits of what the model can support for advancing our mission forward. We have seen too many MIT components moving slowly or getting abandone
```suggestion
However, we believe that we have reached the sustainability limits of what the model can support for advancing our mission forward. We have seen too many MIT licensed components moving slowly or getting abandoned. The community isn't contributing improvements as fast as the problems deserved to be solved.
```

"too many MIT licensed components"? (i.e external to Material-UI?)

2021-02-21 04:40 UTC, mbrookes commented on README.md
> +What should we do? Wait? No! We are using a commercial license to forward the development of the most advanced features, where the MIT model can't.
```suggestion
We are using a commercial license to forward the development of the most advanced features, where the MIT model can't sustain it.
```

2021-02-21 04:40 UTC, mbrookes commented on README.md
> +- Community. This plan contains the MIT components that are sustainable by the contributions of the open-source community. Free and forever.
```suggestion
- **Community**. This plan contains the MIT components that are sustainable by the contributions of the open-source community. Free forever.
```

2021-02-21 04:40 UTC, mbrookes commented on README.md
> +- Pro. This plan contains the features that are at the limit of what the open-source model can sustain. For instance, providing a very comprehensive set of components. From a price perspective, the p
```suggestion
- **Pro**. This plan contains the features that are at the limit of what the open-source model can sustain. For instance, providing a very comprehensive set of components. From a price perspective, the plan is designed to be accessible to most professionals.
```

2021-02-21 04:40 UTC, mbrookes commented on README.md
> +- Premium. This plan contains the most advanced features.
```suggestion
- **Premium**. This plan contains the most advanced features.
```

2021-02-21 04:40 UTC, mbrookes commented on README.md
> +- [XGrid](https://material-ui.com/components/data-grid/#commercial-version), publised under `@material-ui/x-grid`, Commercial license.
```suggestion
- [XGrid](https://material-ui.com/components/data-grid/#commercial-version), publised under `@material-ui/x-grid`, commercially licensed.
```

2021-02-21 15:00 UTC, mbrookes approved these changes

2021-02-22 10:00 UTC, dtassone approved these changes

2021-02-22 12:03 UTC, DanailH approved these changes

2021-02-22 12:34 UTC, merged