[DataGrid] Make column selection translatable
mui-org/material-ui-x pull request #1379
Opened 2021-04-09 02:59 UTC by m4theushw

Closes #1112

2021-04-09 10:31 UTC, oliviertassinari requested changes

2021-04-09 10:31 UTC, oliviertassinari commented on packages/grid/_modules_/grid/constants/localeTextConstants.ts
> +  checkboxSelectionHeaderName: 'Checkbox Selection',
This capitalization would be more consistent

```suggestion
  checkboxSelectionHeaderName: 'Checkbox selection',
```

2021-04-09 10:31 UTC, oliviertassinari commented on packages/grid/_modules_/grid/hooks/features/columns/useGridColumns.ts
> +    checkboxSelection.description = getLocaleText('checkboxSelectionDescription');
`description` is defined as "The description of the column rendered as tooltip if the column header name is not fully displayed". It doesn't seem to be relevant.

How about we simplify it to?

```suggestion
```

2021-04-09 10:35 UTC, oliviertassinari reviewed
I guess @dtassone will be able to bring light on either `hydrateColumns` is the best place to append the value or if it would be better done somewhere else, e.g. in `GridColumnsPanel`.

2021-04-11 22:34 UTC, oliviertassinari approved these changes

2021-04-12 09:54 UTC, dtassone approved these changes

2021-04-12 11:56 UTC, merged