[CHANGELOG] v4.0.0-alpha.27
mui-org/material-ui-x pull request #1524
Opened 2021-04-29 16:18 UTC by dtassone

2021-04-29 17:23 UTC, oliviertassinari requested changes
We miss the update of the version of the packages.

2021-04-29 17:23 UTC, oliviertassinari commented on CHANGELOG.md
> +- ⚡️ Update to Node 12 (#1499) @ZeeshanTamboli
I think that framing the information in this direction would have more utility. 

```suggestion
- ⚡️ Drop support for Node v10(#1499) @ZeeshanTamboli
```

2021-04-29 17:23 UTC, oliviertassinari commented on CHANGELOG.md
> +- [DataGrid] Remove `onAction` APIs (#1453) @DanailH
This is not impacting the MIT version

```suggestion
- [XGrid] Remove `onAction` APIs (#1453) @DanailH
```

2021-04-29 17:23 UTC, oliviertassinari commented on CHANGELOG.md
> +  - Changes on `apiRef.current`.
A bullet point doesn't make sense in its context, it's alone.

2021-04-29 17:23 UTC, oliviertassinari commented on CHANGELOG.md
> +- [DataGrid] Refactor useGridColumnResize (#1380) @DanailH
Same as above 

```suggestion
- [XGrid] Refactor useGridColumnResize (#1380) @DanailH
```

2021-04-29 17:23 UTC, oliviertassinari commented on CHANGELOG.md
> +  - Changes on `apiRef.current`.
Same as above. 

```suggestion
 Changes on `apiRef.current`.
```

2021-04-29 17:23 UTC, oliviertassinari commented on CHANGELOG.md
> +- [DataGrid] refactoring on focus cell and cols (#1421) @dtassone
```suggestion
- [DataGrid] Improve focus management logic (#1421) @dtassone
```

2021-04-29 17:23 UTC, oliviertassinari commented on CHANGELOG.md
> +### Tests
We usual group tests under `### Core` as the second is about the underlying infrastructure that supports the components.

2021-04-29 17:23 UTC, oliviertassinari commented on CHANGELOG.md
> +- [core] upgrade node version from 10 to 12 (#1499) @ZeeshanTamboli
I think that it should be listed under the header for the main packages. It impacts developers directly. Core changes are often second order consequences.

2021-04-30 09:09 UTC, dtassone commented
> We miss the update of the version of the packages.

I think it was easier and less error-prone when it was done automatically. Here you can easily miss the dependencies.

2021-04-30 09:40 UTC, dtassone commented
> > We miss the update of the version of the packages.
> 
> I think it was easier and less error-prone when it was done automatically. Here you can easily miss the dependencies.

That's because I've done it manually.

2021-04-30 10:01 UTC, oliviertassinari commented
> That's because I've done it manually.

I don't understand, [the instructions](https://github.com/mui-org/material-ui-x/blob/master/scripts/README.md#prepare asks for using `yarn release:version`, which does the update automatically.

2021-04-30 10:13 UTC, oliviertassinari approved these changes
Ok, I can't notice anything wrong, I'm in

![github com_mui-org_material-ui-x_releases_edit_v4 0 0-alpha 26 (1)](https://user-images.githubusercontent.com/3165635/116681503-5bd42c00-a9ad-11eb-9986-76a520140606.png)

2021-04-30 10:14 UTC, oliviertassinari commented on CHANGELOG.md
> +_Apr 29, 2021_
```suggestion
_Apr 30, 2021_
```

2021-04-30 10:15 UTC, dtassone commented
Great!!

2021-04-30 10:31 UTC, merged