[DataGrid] Introduce `minWidth` in `ColDef` for columns with fluid width
mui-org/material-ui-x pull request #1954
Opened 2021-06-23 13:05 UTC by ZeeshanTamboli

Closes #1850

Do we want to have this for only fluid columns i.e having `flex` property?

I have also reverted #1816 as said here https://github.com/mui-org/material-ui-x/issues/1850#issuecomment-856154201

2021-06-27 10:46 UTC, oliviertassinari requested changes

2021-06-27 10:46 UTC, oliviertassinari commented on packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx
> +        minWidth: minWidth !== undefined ? minWidth : width,
This min-width on the element has nothing to do with the min-width of #1850. See the benchmark link to better capture what the problem is.

2021-07-06 08:01 UTC, DanailH commented
@ZeeshanTamboli are you planning to work on this PR. I'm asking because there hasn't been much activity in the last 10 days and I am planning to pick it up. Just want to make sure we are not doing double work here 😉

2021-07-06 08:16 UTC, ZeeshanTamboli commented
> @ZeeshanTamboli are you planning to work on this PR. I'm asking because there hasn't been much activity in the last 10 days and I am planning to pick it up. Just want to make sure we are not doing double work here 😉

@DanailH You can take this up, thanks. I have been aiming this PR but got some other priorities lately so haven't found time to work on this. Since I am not sure when I can continue working on this or something else, you can pick this up.

2021-07-07 10:47 UTC, DanailH commented
@ZeeshanTamboli thanks for the quick reply - I'll keep this one open for now and use it as a base - thanks for the effort tho ;)

2021-07-08 12:41 UTC, DanailH commented
I'm closing this PR in favour of that one https://github.com/mui-org/material-ui-x/pull/2101

2021-07-08 12:41 UTC, closed without merging