[docs] Migrate the Rendering section
mui-org/material-ui-x pull request #255
Opened 2020-09-06 18:23 UTC by oliviertassinari

Objective, handle this page: http://0.0.0.0:3001/components/data-grid/rendering/.

2020-09-06 19:05 UTC, mbrookes commented on docs/src/pages/components/data-grid/overview/overview.md
>  The following grid displays 31 columns and 100,000 rows, it's over 3 million cells.
```suggestion
The following grid displays 31 columns and 100,000 rows - over 3 million cells in total.
```

2020-09-10 00:07 UTC, mbrookes requested changes

2020-09-10 00:07 UTC, mbrookes commented on docs/src/pages/components/data-grid/getting-started/getting-started.md
> +Once you purchase a license, you receive a license key.
```suggestion
Once you purchase a license, you'll receive a license key.
```

2020-09-10 00:07 UTC, mbrookes commented on docs/src/pages/components/data-grid/getting-started/getting-started.md
> +We use GitHub issues exclusively as a bugs and feature requests tracker. If you think you have found a bug, or have a new feature idea, please start by making sure it hasn't already been [reported or
```suggestion
We use GitHub issues exclusively as a bug and feature request tracker. If you think you have found a bug, or have a new feature idea, please start by making sure it hasn't already been [reported or fixed](https://github.com/mui-org/material-ui-x/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aclosed). You can search through existing issues and pull requests to see if someone has reported one similar to yours.
```

2020-09-10 00:07 UTC, mbrookes commented on docs/src/pages/components/data-grid/getting-started/getting-started.md
> +We provide a private support channel for the enterprise customers on [Zendesk](https://material-ui.zendesk.com/).
```suggestion
We provide a [private support channel](https://material-ui.zendesk.com/) for enterprise customers.
```

2020-09-10 00:07 UTC, mbrookes commented on docs/src/pages/components/data-grid/getting-started/getting-started.md
> +You can find our public roadmap on this [GitHub project](https://github.com/mui-org/material-ui-x/projects/1). It's organized by quarter.
```suggestion
Here is [the public roadmap](https://github.com/mui-org/material-ui-x/projects/1). It's organized by quarter.
```

2020-09-10 00:07 UTC, mbrookes commented on docs/src/pages/components/data-grid/getting-started/getting-started.md
> +> ⚠️ Disclaimer: We operate in a dynamic environment, and things are subject to change. The information provided is intended to outline the general framework direction. It's intended for informationa
```suggestion
> ⚠️ Disclaimer: We operate in a dynamic environment, and things are subject to change. The information provided is intended to outline the general framework direction, for informational purposes only. We may decide to add or remove new items at any time, depending on our capability to deliver while meeting our quality standards. The development, releases, and timing of any features or functionality remains at the sole discretion of Material-UI. The roadmap does not represent a commitment, obligation, or promise to deliver at any time.
```

2020-09-10 08:40 UTC, dtassone approved these changes

2020-09-10 09:06 UTC, merged