Fix issue #254, focus cell fully visible
mui-org/material-ui-x pull request #256
Opened 2020-09-09 16:33 UTC by dtassone

2020-09-09 17:56 UTC, oliviertassinari requested changes
Should we add a test cases to avoid regressions in the future? Any idea on how we could best write them? For instance, with karma we could call `.getBoundingClientRect()` and make sure the horizontal offset is correct. It should be easy to write, fast to run and easy to debug if there is a regression (hopefully). I think that we could also argue that puppeteer would make it even easier to debug (in case of a regression), however, we would first need to:

- add puppeteer in the CI, otherwise the test has no value
- figure out why the tests are slow to run, I suspect moving from storybook to next.js to run them will help a lot but I have no data to back this (only an intuition that by using code spliting, we will save a lot of time both during runtime in the CI and locally.

I think that we should avoid visual tests for this type of problems, it would be slower to run and less accurate in the assertion.

2020-09-09 17:56 UTC, oliviertassinari commented on packages/grid/x-grid-modules/src/hooks/virtualization/useVirtualColumns.ts
> +      const firstColIndex = visibleColumns.findIndex((col) => col.field === firstCol?.field) + 1;
Is the name `firstColIndex` still accurate?

2020-09-09 18:03 UTC, oliviertassinari commented
@dtassone I have updated the pull request metadata to follow the standard, what do you think about it? The changes:

- Never include the ID of the related issue in the title. 
- Always include the ID of the related issue in the description.
- Use one the auto closing wording supported by GitHub when it make sense https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword.
- Prefix the pull request with the scope. In our case `[DataGrid]`. 
- Add labels specific to the type of the problem it solve. In our case data grid and bug.

2020-09-09 20:16 UTC, oliviertassinari commented
> Fix #254

The behavior seems correctly fixed.

> Should we add a test cases to avoid regressions in the future?

I have found #258. I think that we need a test to avoid regressions, this seems to be a hard problem :)

2020-09-10 08:33 UTC, dtassone commented on packages/grid/x-grid-modules/src/hooks/virtualization/useVirtualColumns.ts
> +      const firstColIndex = visibleColumns.findIndex((col) => col.field === firstCol?.field) + 1;
yes

2020-09-10 08:50 UTC, dtassone commented on packages/grid/x-grid-modules/src/hooks/virtualization/useVirtualColumns.ts
> +      const firstColIndex = visibleColumns.findIndex((col) => col.field === firstCol?.field) + 1;
> I think that we should avoid visual tests for this type of problems, it would be slower to run and less accurate in the assertion.

Well you will need to check the scroll and calculate that the scrollLeft value is less than the offset value of the focused cell by a small amount. Also you will need to press arrow left a few times until the focus move to a cell well outside the viewport. Then go back to the first column....
For me, it's the kind of test that will be very difficult to understand and visualize in karma.

2020-09-10 08:51 UTC, dtassone commented
> > Fix #254
> 
> The behavior seems correctly fixed.
> 
> > Should we add a test cases to avoid regressions in the future?
> 
> I have found #258. I think that we need a test to avoid regressions, this seems to be a hard problem :)

#258 is another issue and he's still there

2020-09-10 10:10 UTC, oliviertassinari commented on packages/grid/x-grid-modules/src/hooks/virtualization/useVirtualColumns.ts
> +      const firstColIndex = visibleColumns.findIndex((col) => col.field === firstCol?.field) + 1;
@dtassone I think that we can only call `getBoundingClientRect` and make sure `.left === 0`, I don't see the need to test scroll or only other value. Yes, the test would need to use the keyboard to get into the right condition. This sounds perfect, reproducing the real-life use case.

Regarding the pain to visualize in Karma, I agree with you. It's why I said: "I think that we could also argue that puppeteer would make it even easier to debug". Puppeteer has more potential, but it's yet to be untapped by making it something we can rely on (it's not the case yet, no integration in the CI).

2020-09-10 10:13 UTC, oliviertassinari commented on packages/grid/x-grid-modules/src/hooks/virtualization/useVirtualColumns.ts
> +      const firstColIndex = visibleColumns.findIndex((col) => col.field === firstCol?.field) + 1;
Well `=== 0` would work if we remove the body margin, a quick POC:

<img width="1224" alt="Capture d’écran 2020-09-10 à 12 12 07" src="https://user-images.githubusercontent.com/3165635/92716276-e86aa500-f35e-11ea-835f-0e27d60990ef.png">

2020-09-10 10:17 UTC, oliviertassinari commented
> #258 is another issue and he's still there

Yeah, agree, I have only open the issue to keep track of it, I doubt it's important for us NOW (maybe later). And it's definitely unrelated to this one. My only objective was to make the point that regression tests are likely valuable for this problem.

2020-09-10 12:46 UTC, dtassone commented on packages/grid/x-grid-modules/src/hooks/virtualization/useVirtualColumns.ts
> +      const firstColIndex = visibleColumns.findIndex((col) => col.field === firstCol?.field) + 1;
Testing the component within the doc is probably not the best. As the doc can influence on the component behavior, let say you have a css override in the doc that break/fix the component.

2020-09-10 15:02 UTC, merged