[DataGrid] Last column miss padding
mui-org/material-ui-x pull request #748
Opened 2020-12-15 12:24 UTC by ZeeshanTamboli

Fixes #442 

Added an empty div element to show space at end above scroll on the last column. This especially happens if there is a menu item on a NUMERIC column type i.e when the menu is on the left side.

I tried padding or reducing the width of column header for last column like this,
```js
const isLastColumn = idx === columns.length - 1;
const removeScrollWidth = isLastColumn && hasScroll.y && hasScroll.x;
const width = removeScrollWidth ? Math.abs(col.width! - scrollSize * 2) : col.width!;
```

But then the text is overflowing like:
![Screenshot 2020-12-15 at 4 34 34 PM](https://user-images.githubusercontent.com/20900032/102214016-a15ff300-3efd-11eb-8940-43119bf7a2ff.png)

----
Now after fix:
![Screenshot 2020-12-15 at 5 44 27 PM](https://user-images.githubusercontent.com/20900032/102214083-b76db380-3efd-11eb-90cb-de0aaf19fa31.png)

If otherwise a better solution, help would be appreciated!

2020-12-15 14:30 UTC, dtassone commented
The resize of the last column is not great

2020-12-15 15:32 UTC, oliviertassinari commented
> The resize of the last column is not great

@dtassone Are you reporting a regression or a different problem, isolated to the one this pull request aims to fix?

2020-12-15 23:39 UTC, oliviertassinari requested changes
I don't think that we are nowhere near a solution with the extra `<div>` element. I think that another part of the issue is that the `width` option we set on the last column isn't respected, the scrollbar eats some of it. So I think that the solution is to compensate for the width of the scrollbar anytime it's visible

2020-12-15 23:39 UTC, oliviertassinari commented on packages/grid/_modules_/grid/components/columnHeaders/ColumnHeadersItemCollection.tsx
> +        isLastColumn={isLastColumn}
A detail coding style convention, we generally don't use `is` for boolean.

```suggestion
        lastColumn={lastColumn}
```

2020-12-16 10:49 UTC, ZeeshanTamboli commented
> I don't think that we are near a solution with the extra `<div>` element. I think that another part of the issue is that the `width` option we set on the last column isn't respected for cells (It's ok with the header), the scrollbar eats some of it. So I think that the solution is to compensate for the width of the scrollbar anytime it's visible

In the `master` branch code, it is explicitly added to remove the scroll width for a row cell at: 
https://github.com/mui-org/material-ui-x/blob/3a02879fc169a3b20ac65a758e13ec416702bb70/packages/grid/_modules_/grid/components/RowCells.tsx#L56-L58
That's the reason for the issue I think. By reducing this cell width, the alignment differs between row cell and header.

By compensating the scroll, do you mean to make the row and header column width equal?
So for that I tried the following code change instead in `useContainerProps.ts` file at line 77,
```js
const viewportSize = {
        width: windowSizesRef.current!.width,
        height: options.autoHeight
          ? rowsCount * rowHeight
          : windowSizesRef.current!.height,
      };
```
Resulting in:

![Hnet com-image](https://user-images.githubusercontent.com/20900032/102337940-265c1280-3fb9-11eb-986b-d6d3166f774f.gif)
where the scroll is overlapping which does not look good I think.

Or do you mean having a `scroll` event listener and _only_ when scrolling, change the width to make it look like it is currently in release. Or is it something else?

2020-12-16 12:13 UTC, oliviertassinari commented
@ZeeshanTamboli I think that you can compare with ag-Grid to see what I think the correct behavior should be. I think that there are two important cases to consider: mobile & when the vertical scrollbar is present vs. when it's not.

2020-12-16 13:26 UTC, dtassone commented
This is a concern only when you have a transparent scrollbar.
Native behaviour is fine in chrome, I believe.

2020-12-16 13:31 UTC, dtassone commented
Transparent scrollbars are meant to overlap

2020-12-16 13:48 UTC, oliviertassinari commented
@dtassone I think that you would need to be more specific. I believe that right, now, it's only correct on macOS when the default scrollbar setting is used. On all the other cases, Windows, mobile, macOS with scrollbar that reserve space (my config), it's wrong.

2020-12-17 10:15 UTC, dtassone commented
> @dtassone I think that you would need to be more specific. I believe that right, now, it's only correct on macOS when the default scrollbar setting is used. On all the other cases, Windows, mobile, macOS with scrollbar that reserve space (my config), it's wrong.

Hmm ok, I'm not sure I properly understand the issue 🤔

2020-12-17 11:06 UTC, oliviertassinari commented
> Hmm ok, I'm not sure I properly understand the issue 🤔

@dtassone Are the current vs. expected screenshots of #442 clearer?

2021-01-16 09:43 UTC, oliviertassinari commented
The effort has been stale for a while, I'm closing. @ZeeshanTamboli Thanks for giving it a try

2021-01-16 09:43 UTC, closed without merging