[DataGrid] Make autoHeight work
mui-org/material-ui-x pull request #930
Opened 2021-01-26 14:23 UTC by DanailH

Ok so the PR is smaller than expected 😅

SO what I did - > I tried moving the `<AutoSizer>` component down to the `<GridWindow>` so basically 

```
<AutoSizer>
  <GridWindow ref={windowRef}>
    <Viewport ref={renderingZoneRef} />
  </GridWindow>
</AutoSizer>
```

The issue with that approach is that the `apiRef` then is messed up, meaning the trid is rendered before all the methods in the `apiRef` are loaded. The `AutoSizer` prevents this because it doesn't render the children if the container doesn't have dimensions (that is not part of the state of the grid, it comes from an internally kept state inside the `AutoSizer` itself). 

I tried replicating the same logic in the `GridRoot` component as that's the one that is the entry point after moving the `AutoSizer` down. It can be done with a little bit of abstraction and suffering logic around.

But then I tried to fix it by just changing the dimensions the `AutoSizer` adds and it seems to work. I tested it with the demos in the Storybook and in the Docs and it seems to be fine.

2021-01-26 15:26 UTC, oliviertassinari requested changes
height 0 is important, it can't be removed. Did you plan the line?

2021-01-26 15:28 UTC, oliviertassinari commented
> Did you plan the line?

We land on #350 but it's really noisy. If the fix was one line, it would have been the inverse of the change of this PR.

2021-01-26 15:31 UTC, oliviertassinari commented
> The issue with that approach is that the apiRef then is messed up, meaning the trid is rendered before all the methods in the apiRef are loaded.

I had experienced the same the last time I had a quick look at the problem. IMHO, it's an issue with the `apiRef` and the state structure of the grid. I suspect the same underlying structure issue as with strict mode.

2021-01-26 16:05 UTC, dtassone commented
Fix #604 

The total height of the grid component is stored in the state `state.containerSizes.totalSizes.height` so have you tried adding a div before Autosizer and apply the height in an effect...?

2021-01-26 16:07 UTC, oliviertassinari commented
> The total height of the grid component is stored in the state state.containerSizes.totalSizes.height so have you tried adding a div before Autosizer and apply the height in an effect?

Isn't that hiding the root issue? Shouldn't reproduce the approach of ag-Grid?

2021-01-26 16:08 UTC, oliviertassinari commented
Do we even need Autosize when autoHeight is set?

2021-01-26 16:12 UTC, DanailH commented
> The total height of the grid component is stored in the state `state.containerSizes.totalSizes.height` so have you tried adding a div before Autosizer and apply the height in an effect?

Even if that works (I'll try it) it would be better to move the `AutoSizer` down because the part that has a "dynamic" height is the rows. The rest is static so it shouldn't be dependent on it. I can try and solve the issue with the missing methods in the `apiRef`.

@oliviertassinari thanks for sending the ticket and the PR I'll check them.

2021-01-26 16:33 UTC, dtassone commented
> > The total height of the grid component is stored in the state `state.containerSizes.totalSizes.height` so have you tried adding a div before Autosizer and apply the height in an effect?
> 
> Even if that works (I'll try it) it would be better to move the `AutoSizer` down because the part that has a "dynamic" height is the rows. The rest is static so it shouldn't be dependent on it. I can try and solve the issue with the missing methods in the `apiRef`.
> 

Yes, it should be fine but it's a bigger refactoring. 
I think, anyhow, we will need to wrap autosizer with a div, and do a bit of a hack either like this workaround or by putting the height 🤔 
https://github.com/mui-org/material-ui-x/issues/604#issuecomment-756499141

2021-01-27 09:43 UTC, DanailH commented
Ok I spend some time yesterday investigating more in-depth how the `apiRef` is being built. So it is created [HERE](https://github.com/mui-org/material-ui-x/blob/master/packages/grid/_modules_/grid/GridComponent.tsx#L60). Then we have the grid state initializer [HERE](https://github.com/mui-org/material-ui-x/blob/master/packages/grid/_modules_/grid/GridComponent.tsx#L61) and that one adds the basic state API. After that, the rest of the hooks are fired but they don't add their methods to the `apiRef` instance immediately, as the state does.

So basically what I'm saying is that line [HERE](https://github.com/mui-org/material-ui-x/blob/master/packages/grid/_modules_/grid/components/AutoSizer.tsx#L152) in the `AutoSizer` is the one that "saves" it from throwing errors because of missing APIs. 

On the initial render the `apiRef` only has the default state API and on every continent render it has all the rest APIs. That's why if I move the `AutoSizer` things start to break.

One solution will be to keep that check on the `GridComponent` lvl, or check if the `apiRef` has all the needed methods in it, which would be better, and then render the grid.

The last option and the most correct one would be to fix the problem at the source, a.k.a make sure that after each hook the API is correctly added to the `apiRef`, which is a different problem from the `autoHeight` issue.

2021-01-27 15:31 UTC, DanailH commented
Ok, I've updated the solution and added a test case.

We had a call with @dtassone to discuss potential solutions and the `apiRef`. Since the strict mode issue will have to be fixed as well it would be better to do that as part of the strict mode PR, not this one. The solution here was to add a wrapper around the grid and keep the `AutoSizer` where it currently is (for now at least). Once we have solved the problem with the `apiRef` we can have the effort to move the `AutoSizer` and calculate the dimensions of the grid more reliably.

2021-01-27 16:15 UTC, oliviertassinari reviewed
Did you try to apply the same method by replacing the current AutoSizer with a NoSsr component (to delay by one effect) and move deeper in the DOM the AutoSizer?

2021-01-27 17:38 UTC, dtassone commented
Ok I have made some progress with the strict mode, and I have 2 potential solutions for the issue with the missing method on initial start. 
1. Split the current hooks, in 2, one part for the api and one part to coordinate the component. 
Ie.  we split useRows, in 2 useRowsApi and useRows
We then call useSomethingApi in useApiRef, so the apiRef has all its methods.
2. We initialize the apiRef with a default GridApi implementing all members in useApiRef

2021-01-27 17:39 UTC, dtassone approved these changes

2021-01-27 17:41 UTC, dtassone commented on packages/grid/_modules_/grid/components/containers/GridContainer.tsx
> +  return gridOptions.autoHeight ? (
Why is it only an issue for auto height?

2021-01-27 17:42 UTC, dtassone commented on packages/grid/_modules_/grid/components/containers/GridContainer.tsx
> +      const gridWrapperElement: HTMLDivElement = gridWrapperDiv.querySelector('div')!;
Are you getting the child of the wrapper here?

2021-01-27 22:48 UTC, oliviertassinari requested changes
It's not working. I have taken the reproduction of #344 and use the package version. It grows forever: https://codesandbox.io/s/brave-chatelet-56z4o?file=/src/Demo.js. It's a regression.

It sounds like we need to add a test case in the CI for #344. Oops, I should have done it in my #350 PR 😇. It's still not too late, quite the opposite :).

2021-01-28 09:40 UTC, DanailH commented
> Did you try to apply the same method by replacing the current AutoSizer with a NoSsr component (to delay by one effect) and move deeper in the DOM the AutoSizer?

No, I didn't, I wasn't aware that that is an option. We've been discussing fixing the `apiRef` not having a workaround. I've checked the other PR and continue working on it. After all, what is in that PR was what I wanted to do in the first place. If everyone is ok with using `NoSsr` and basically loading the grid on the second `useEffect` the other solution is better.

2021-01-28 09:43 UTC, DanailH commented
I'm closing this PR in favour of https://github.com/mui-org/material-ui-x/pull/940

2021-01-28 09:43 UTC, closed without merging

2021-01-28 09:47 UTC, oliviertassinari commented
> If everyone is ok with using NoSsr and basically loading the grid on the second useEffect

True, I have used NoSsr to move faster in the POC, we don't necessarily have to use the component, we could unbundle it and make the useEffect sequence more explicit with a new custom component.