[Docs] Filter doc more
mui-org/material-ui-x pull request #945
Opened 2021-01-28 17:57 UTC by dtassone

2021-01-28 18:09 UTC, mbrookes requested changes

2021-01-28 18:09 UTC, mbrookes commented on docs/src/pages/components/data-grid/filtering/filtering.md
> +As in the sort feature, filter can be run server side by setting the `filterMode` prop to `server`, and implementing the `onFilterChange` handler.
```suggestion
As with the sort feature, filtering can be run server side by setting the `filterMode` prop to `server`, and implementing the `onFilterChange` handler.
```

2021-01-28 18:09 UTC, mbrookes commented on docs/src/pages/components/data-grid/filtering/filtering.md
> +The rating column contains new `From` operator as you can see in the filter panel.
```suggestion
The rating column contains a new `From` operator, as you can see in the filter panel.
```

2021-01-28 18:09 UTC, mbrookes commented on docs/src/pages/components/data-grid/filtering/filtering.md
> +In this demo, you will see how to create a complete new operator for a specific column.
```suggestion
In this demo you will see how to create a complete new operator for a specific column.
```

2021-01-28 18:09 UTC, mbrookes commented on docs/src/pages/components/data-grid/filtering/filtering.md
> +As you can see in the filter panel, the `totalPrice` column only contains 2 operators `<`, `>`, and the input field is prefixed with `$`.
```suggestion
As you can see in the filter panel, the `totalPrice` column only contains 2 operators `<`, & `>`, and the input field is prefixed with `$`.
```

2021-01-28 18:09 UTC, mbrookes commented on docs/src/pages/components/data-grid/filtering/filtering.md
> +In this demo, you will see how to extend an existing column type, add your own filter operators with filter input value props.
```suggestion
In this demo you will see how to extend an existing column type, adding your own filter operators with filter input value props.
```

2021-01-28 18:09 UTC, mbrookes commented on docs/src/pages/components/data-grid/filtering/filtering.md
> +In this demo, you will see how to reuse the numeric filter and customize the input filter value component.
```suggestion
In this demo you will see how to reuse the numeric filter and customize the input filter value component.
```

2021-01-28 19:52 UTC, oliviertassinari requested changes

2021-01-28 19:52 UTC, oliviertassinari commented on docs/src/pages/components/data-grid/filtering/ColumnTypeFilteringGrid.tsx
> +export default function NewColumnTypes() {
```suggestion
export default function ColumnTypeFilteringGrid() {
```

2021-01-28 19:52 UTC, oliviertassinari commented on docs/src/pages/components/data-grid/filtering/ColumnTypeFilteringGrid.tsx
> +import { InputAdornment } from '@material-ui/core';
```suggestion
import InputAdornment from '@material-ui/core/InputAdornment';
```

2021-01-28 19:52 UTC, oliviertassinari commented on packages/grid/_modules_/grid/components/panel/filterPanel/FilterInputValue.tsx
> +  const inputProps = applying ? { endAdornment: <LoadIcon /> } : others['inputProps'];
It's used as `InputProps` not `inputProps`.

```suggestion
  const InputProps = applying ? { endAdornment: <LoadIcon /> } : others.InputProps;
```

2021-01-28 19:52 UTC, oliviertassinari commented on docs/src/pages/components/data-grid/filtering/ServerFilterGrid.tsx
> +  );
This fetching logic is not correct. A new request needs to cancel the result of a previous one. Unmounting also needs to cancel requests. I would recommend this pattern: https://material-ui.com/components/data-grid/rows/#server-side-sorting

2021-01-28 19:52 UTC, oliviertassinari commented on docs/src/pages/components/data-grid/filtering/ServerFilterGrid.tsx
> +import * as React from 'react';
We try to import React first. I believe developers are used to this convention and unconsciously have learn to ignore this import.

```suggestion
import * as React from 'react';
import {
  ColDef,
  DataGrid,
  FilterModelParams,
  RowModel,
} from '@material-ui/data-grid';
```

2021-01-28 19:52 UTC, oliviertassinari commented on docs/src/pages/components/data-grid/filtering/CustomRatingOperator.tsx
> +export default function CustomRatingOperator() {
```suggestion

export default function CustomRatingOperator() {
```

2021-01-28 19:52 UTC, oliviertassinari commented on docs/src/pages/components/data-grid/filtering/filtering.md
> +As with the sort feature, filtering can be run server side by setting the `filterMode` prop to `server`, and implementing the `onFilterChange` handler.
I don't see why we should mention sorting over pagination or else. I have also fixed the name of the prop, it's `onFilterModelChange`.

```suggestion
Filtering can be run server-side by setting the `filterMode` prop to `server`, and implementing the `onFilterModelChange` handler.
```

2021-01-28 19:52 UTC, oliviertassinari commented on docs/src/pages/components/data-grid/filtering/filtering.md
> +  onFilterModelChange={onFilterChange}
I think that renaming variable like this creates confusion

```suggestion
  onFilterModelChange={onFilterModelChange}
```

2021-01-28 19:52 UTC, oliviertassinari commented on docs/src/pages/components/data-grid/filtering/filtering.md
> +  onFilterModelChange={onFilterChange}
or if we want to follow the popular handle convention:
```suggestion
  onFilterModelChange={handleFilterModelChange}
```

2021-01-29 11:36 UTC, oliviertassinari approved these changes
I have left two details that can improve the existing demos (less confusion & more performant demos), otherwise, looks good.

2021-01-29 11:36 UTC, oliviertassinari commented on docs/src/pages/components/data-grid/filtering/ColumnTypeFilteringGrid.tsx
> +  React.useEffect(() => {
It looks like a `useMemo` would be enough. It would avoid a rerendering.

2021-01-29 11:36 UTC, oliviertassinari commented on docs/src/pages/components/data-grid/filtering/ColumnTypeFilteringGrid.tsx
> +        columns={cols}
I think that we should ban shortcuts, at least for the documentation :) 

```suggestion
        columns={columns}
```

2021-01-29 11:58 UTC, oliviertassinari approved these changes

2021-01-29 13:45 UTC, merged